/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.k00241934.typingtutor;

import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author ross1
 */
public class AppLauncherJFRame extends javax.swing.JFrame {

	/**
	 * Creates new form AppLauncher
	 */

	public AppLauncherJFRame() {
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        welcomejLabel = new javax.swing.JLabel();
        lauchAsGuestjButton = new javax.swing.JButton();
        LoginButton = new javax.swing.JButton();
        createNewUserjButton = new javax.swing.JButton();
        saveDatajButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("App Launcher");

        welcomejLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        welcomejLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        welcomejLabel.setText("Welcome Too Typing Tutor");

        lauchAsGuestjButton.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lauchAsGuestjButton.setText("Launch As Guest");
        lauchAsGuestjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lauchAsGuestjButtonActionPerformed(evt);
            }
        });

        LoginButton.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        LoginButton.setText("Login");
        LoginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoginButtonActionPerformed(evt);
            }
        });

        createNewUserjButton.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        createNewUserjButton.setText("Create new user");
        createNewUserjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createNewUserjButtonActionPerformed(evt);
            }
        });

        saveDatajButton.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        saveDatajButton.setText("save Data");
        saveDatajButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveDatajButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(welcomejLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
                    .addComponent(lauchAsGuestjButton, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
                    .addComponent(LoginButton, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
                    .addComponent(createNewUserjButton, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
                    .addComponent(saveDatajButton, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE))
                .addGap(27, 27, 27))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addComponent(welcomejLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lauchAsGuestjButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LoginButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(createNewUserjButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(saveDatajButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
//This JButton action creates a new user guest and makes typing tutor visable and applaucher not visable
    private void lauchAsGuestjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lauchAsGuestjButtonActionPerformed
		var typingTutor = new TypingTutorJFrame(this, new UserAccount());
		typingTutor.setVisible(true);
		this.setVisible(false);
    }//GEN-LAST:event_lauchAsGuestjButtonActionPerformed
// This action set the login gui visable and makes the applAucher not visable
    private void LoginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoginButtonActionPerformed
        var loginJframe= new LoginUserAccountJFrame(this);
		loginJframe.setVisible(true);
		this.setVisible(false);
    }//GEN-LAST:event_LoginButtonActionPerformed
    // this button saves the user progress and the next login they will contuine where they left off 
    private void saveDatajButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveDatajButtonActionPerformed
		try {
			// calls the save method 
			UserAccountRepository.save();
			
		} catch (IOException ex) {
			// puts the data into the right username location so when the user logs in the data is saved
			Logger.getLogger(AppLauncherJFRame.class.getName()).log(Level.SEVERE, null, ex);
		}
    }//GEN-LAST:event_saveDatajButtonActionPerformed
// This method make the create user jframe visable 
    private void createNewUserjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createNewUserjButtonActionPerformed
       var createJframe= new CreateUserAccountJFrame(this);
		createJframe.setVisible(true);
		this.setVisible(false);
    }//GEN-LAST:event_createNewUserjButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton LoginButton;
    private javax.swing.JButton createNewUserjButton;
    private javax.swing.JButton lauchAsGuestjButton;
    private javax.swing.JButton saveDatajButton;
    private javax.swing.JLabel welcomejLabel;
    // End of variables declaration//GEN-END:variables
}
