/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.k00241934.typingtutor;

/**
 *
 * @author ross1
 */
public class CreateUserAccountJFrame extends javax.swing.JFrame {

	AppLauncherJFRame appLauncher;

	public CreateUserAccountJFrame(AppLauncherJFRame appLauncher) {
		this.appLauncher = appLauncher;

		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        createJButton = new javax.swing.JButton();
        cancelJButton = new javax.swing.JButton();
        errorJLabel = new javax.swing.JLabel();
        PasswordTextField = new javax.swing.JTextField();
        passwordLabel = new javax.swing.JLabel();
        userNameTextField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        createUserLabel = new javax.swing.JLabel();
        confirmPasswordjTextField = new javax.swing.JTextField();
        confirmPasswordjLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        createJButton.setText("Create");
        createJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createJButtonActionPerformed(evt);
            }
        });

        cancelJButton.setText("Cancel");
        cancelJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelJButtonActionPerformed(evt);
            }
        });

        errorJLabel.setForeground(new java.awt.Color(204, 0, 51));

        passwordLabel.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        passwordLabel.setText("Password:");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel1.setText("user name:");

        createUserLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        createUserLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        createUserLabel.setText("Create User");

        confirmPasswordjLabel.setText("confirm password");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(109, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(createJButton)
                        .addGap(29, 29, 29)
                        .addComponent(cancelJButton))
                    .addComponent(errorJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(100, 100, 100))
            .addGroup(layout.createSequentialGroup()
                .addGap(96, 96, 96)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(confirmPasswordjLabel)
                    .addComponent(confirmPasswordjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(104, 104, 104)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(createUserLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 191, Short.MAX_VALUE)
                        .addComponent(userNameTextField)
                        .addComponent(jLabel1)
                        .addComponent(passwordLabel)
                        .addComponent(PasswordTextField))
                    .addContainerGap(105, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(204, Short.MAX_VALUE)
                .addComponent(errorJLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(confirmPasswordjLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(confirmPasswordjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cancelJButton)
                    .addComponent(createJButton))
                .addGap(13, 13, 13))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(75, 75, 75)
                    .addComponent(createUserLabel)
                    .addGap(18, 18, 18)
                    .addComponent(jLabel1)
                    .addGap(3, 3, 3)
                    .addComponent(userNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(18, 18, 18)
                    .addComponent(passwordLabel)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(PasswordTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(94, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cancelJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelJButtonActionPerformed
		cancelJButtonActionPerformed();
// TODO add your handling code here:
    }//GEN-LAST:event_cancelJButtonActionPerformed

    private void createJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createJButtonActionPerformed
		createJButtonActionPerformed();
// TODO add your handling code here:
    }//GEN-LAST:event_createJButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField PasswordTextField;
    private javax.swing.JButton cancelJButton;
    private javax.swing.JLabel confirmPasswordjLabel;
    private javax.swing.JTextField confirmPasswordjTextField;
    private javax.swing.JButton createJButton;
    private javax.swing.JLabel createUserLabel;
    private javax.swing.JLabel errorJLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel passwordLabel;
    private javax.swing.JTextField userNameTextField;
    // End of variables declaration//GEN-END:variables

	private void cancelJButtonActionPerformed() {

	}

	private void createJButtonActionPerformed() {
		var username = this.userNameTextField.getText();
		var password = this.PasswordTextField.getText();
		var confirmPassword = this.confirmPasswordjTextField.getText();
		//get confirm password
		if (username.equals("")) {
			this.errorJLabel.setText("The username canNot be Blank");
		} else if (!password.equals(confirmPassword)) {
			this.errorJLabel.setText("Passwords must match");
		} else if (UserAccountRepository.CheckUserAccountWithUserNameExists(username)) {
			this.errorJLabel.setText("user name is taken please pick another name");
		} else {
			UserAccountRepository.getUsersAcconts().add(new UserAccount(username, password));
			// lanuch Login
			var loginJframe = new LoginUserAccountJFrame(this.appLauncher);
			loginJframe.setVisible(true);
			this.setVisible(false);
		}
	}
}
